# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item_table',
        ),
    ]
